### PR TITLE
Add option to specify consistency of migrations

### PR DESCRIPTION
**Pull request by backjo**
This change is [Reviewable](https://reviewable.io/reviews/patka/cassandra-migration/20)

### CODE REVIEW

**Comment by dpetzel** [comment]
This would be great, I found myself wanting this recently as well. Having this available would make things a bit easier on us.

**Comment by patka** [comment]
Hi,

this is already implemented in the upcoming version branch. Unfortunately  I am currently quite busy with my family that I barely find any time to continue. I hope this will change soon. Sorry for the inconvenience.

Cheers
Patrick

**Comment by Vity01** [comment]
@backjo nice improvement, but could you also update cassandra-migration-spring-boot-starter to add the property? 
@patka Could you please review it and release it?

**Comment by Vity01** [comment]
He also created a new constructor so it does not change compatibility at all.
Maybe a better idea is to define configurer for a statement - it will be ready for setting another property, not just the consistency-level.

**Comment by patka** [comment]
That is what will come in version 3.

**Comment by patka** [comment]
Despite the fact that the maven badge says something else (the content seems to be cached now by Github?), I released version 2.2.0 yesterday that contains this change.

**Comment by Vity01** [comment]
@patka Thank you!

**Pull request merged**
