### PR TITLE
Check that the schema is in agreement after a schema change

### PR DESCRIPTION
**Pull request by pierre-l**
It would be nice to use the "agreement check" feature from the Datastax Java driver.
Here is an implementation proposal.

### CODE REVIEW

**Comment by pierre-l** [comment]
Oh and I forgot: thank you for your work @patka :)

**Comment by patka** [comment]
Hello,

that actually makes sense :) Thanks for the contribution and pointing that out, I will have a look at it in the coming days and come back to you.

Cheers
Patrick

**Comment by pierre-l** [comment]
TBH I created it because I wanted this to be explicit, but now that you say this I do agree and I think I found a way that is a bit nicer. I'll write another pull request soon.

**Comment by patka** [comment]
I thought about returning a boolean value from the executeStatement method that indicates if the change was successful or not, which I think is valid as the whole purpose of the library is to change the schema. This would require a change to the calling method as you need to jump out of the loop and basically need to execute what is now happening in the catch block. If you have another/better solution, I am happy to see it.

**Comment by pierre-l** [comment]
I am among the developers who hate using booleans to assess the correct execution of a process, but I am not sure of how purely dogmatic it is. I also am among these who tend to avoid the use of RuntimeException because I find it too implicit but I can see that you and the developers of the Datastax driver do not, so feel free to disagree :)

Still, would you want to guide your users more by providing richer info upon an upgrade failure I would use exceptions as it would suit a broader range of situations IMHO.

Another alternative I would enjoy would be the use of a dedicated "MigrationReport" class or something like this. It could provide info like what was the version before the migration, what version it is now, what was the cause of the failure, etc.

What do you think about this?

**Comment by patka** [comment]
Well, you won't hear any argument from me on the part about booleans as return values in this context :)
Regarding checked exception, here I am more with Robert Martin in a way that checked exceptions proved to be a pain to deal with more often than not, especially in scenarios where there is no real way to deal with it. I am not saying you shouldn't do proper exception handling but I have seen so much code that either swallows or simply logs exceptions because they have to be dealt with that I highly question the added value of making it explicit. But in the end this is a matter of philosophy.

The MigrationReport or MigrationSummary is something I thought about myself and I would consider a good option. Like this you might even get rid of exceptions at all but you have to trust the user to check the result.

**Comment by pierre-l** [comment]
Hi patka,
I just wanted to keep you updated: I'm not sure when I will have time to do this but the company I work for will require it at some point so it will happen someday ;)

**Comment by patka** [comment]
Hi,
don't worry about it. I think I did a first implementation. I am just not sure if I pushed it already. I will check and you can than have a look it if fits your need :)

**Comment by pierre-l** [comment]
Wow, cool! Thanks!

**Pull request merged**
