### PR TITLE
Add ability to choose execution profile (by configuration parameter) …

### PR DESCRIPTION
**Pull request by rvgulinski**
…used for schema migration statements. Profiles concept is described here https://docs.datastax.com/en/developer/java-driver/4.0/manual/core/configuration/.

### CODE REVIEW

**Comment by rvgulinski** [comment]
Thanks, I am back to this after a longer weekend :) Sure I will change code according to your comment. Anyway is there any chance for released version including that change in the near future?

**Comment by patka** [comment]
Long weekend sounds nice. Hope you enjoyed it :) 

Yes, the release process is not complicated. Once the feature is merged, I can do a release in the next couple of days.

**Comment by rvgulinski** [comment]
Yes, thanks I did enjoy it a lot.

It is good to hear that your release process is fluent. Changes are commited so I'm looking forward for next version.
Have a nice day and thanks for this cool library.

**Comment by patka** [comment]
I am glad the library is useful :)
The feature is released in version 2.4.0_v4. Check it out and let my know in case there are any issues.

**Pull request merged**
